### ISSUE TITLE
Project is dead

### ISSUE THREAD

**Issue by floriansegginger** [mwaylabs/The-M-Project#147]
The project is completely dead, thank you for abandoning it

**Comment by MathiasTim** [comment]
Hey, if you are interested in why we moved on, we wrote a blog post earlier this year: http://blog.mwaysolutions.com/2015/09/10/generator-m-ionic-html5-mobile-app-development-evolved/

Any further information you can find here: https://github.com/mwaylabs/generator-m-ionic

**Comment by wulfsolter** [comment]
I still use it occasionally. Our fork of Espresso is updated to run on Node v4.1.x but we've not added much new functionality. Ionic (Angular) is our preferred platform looking forward - jQuery UI / Mobile was really good but there are limitations Angular steps beyond.

**Comment by wulfsolter** [comment]
https://github.com/WherewolfNZ/Espresso
